//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoTrade.MarketData.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleDependency
    {
        public int ID { get; set; }
        public int ModuleID { get; set; }
        public int DependentOnModuleID { get; set; }
        public System.DateTime Created { get; set; }
    
        public virtual Module DependentOnModule { get; set; }
    }
}
