//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoTrade.MarketData.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subscription
    {
        public Subscription()
        {
            this.Stocks = new HashSet<Stock>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public bool Active { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public System.DateTime Created { get; set; }
        public System.TimeSpan UpdateInterval { get; set; }
        public int DataProviderID { get; set; }
        public System.DateTime Modified { get; set; }
    
        public virtual ICollection<Stock> Stocks { get; set; }
        public virtual DataProvider DataProvider { get; set; }
    }
}
