//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoTrade.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoTrade.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The app setting {0} was not found, and no default value was provided..
        /// </summary>
        internal static string AppSettingMissingMessageFormat {
            get {
                return ResourceManager.GetString("AppSettingMissingMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred loading the configuration for an assembly. Details: {0}.
        /// </summary>
        internal static string AssemblyConfigurationExceptionMessage {
            get {
                return ResourceManager.GetString("AssemblyConfigurationExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An assembly with the name {0} has not been loaded into the application domain..
        /// </summary>
        internal static string AssemblyNotFoundExceptionMessage {
            get {
                return ResourceManager.GetString("AssemblyNotFoundExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The attribute {0} on element {1} does not have a value..
        /// </summary>
        internal static string AttributeValueNullExceptionMessage {
            get {
                return ResourceManager.GetString("AttributeValueNullExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bootstrapper completed successfully..
        /// </summary>
        internal static string BootstrapperCompletedMessage {
            get {
                return ResourceManager.GetString("BootstrapperCompletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully created Unity container..
        /// </summary>
        internal static string ContainerCreatedMessage {
            get {
                return ResourceManager.GetString("ContainerCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing modules....
        /// </summary>
        internal static string InitializingModulesMessage {
            get {
                return ResourceManager.GetString("InitializingModulesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The format of the type name {0} is invalid. The type name should be a fully-qualified assembly name..
        /// </summary>
        internal static string InvalidTypeNameFormatExceptionMessage {
            get {
                return ResourceManager.GetString("InvalidTypeNameFormatExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully created log4net logger..
        /// </summary>
        internal static string LoggerCreatedMessage {
            get {
                return ResourceManager.GetString("LoggerCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An attribute with the name {0} was expected to be found on the element {1}..
        /// </summary>
        internal static string MissingAttributeExceptionMessage {
            get {
                return ResourceManager.GetString("MissingAttributeExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully created module catalog..
        /// </summary>
        internal static string ModuleCatalogCreatedMessage {
            get {
                return ResourceManager.GetString("ModuleCatalogCreatedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create Unity container. Container is null..
        /// </summary>
        internal static string NullContainerMessage {
            get {
                return ResourceManager.GetString("NullContainerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create logger. Logger is null..
        /// </summary>
        internal static string NullLoggerMessage {
            get {
                return ResourceManager.GetString("NullLoggerMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create module catalog. Catalog is null..
        /// </summary>
        internal static string NullModuleCatalogMessage {
            get {
                return ResourceManager.GetString("NullModuleCatalogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The response object returned by the request to the url {0} returned null..
        /// </summary>
        internal static string NullWebResponseStreamMessageFormat {
            get {
                return ResourceManager.GetString("NullWebResponseStreamMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A type with the name {0} was not found..
        /// </summary>
        internal static string TypeNotFoundExceptionMessage {
            get {
                return ResourceManager.GetString("TypeNotFoundExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected node was found in the module registrations xml - Expected = {0}, Actual = {1}..
        /// </summary>
        internal static string UnexpectedNodeExceptionMessage {
            get {
                return ResourceManager.GetString("UnexpectedNodeExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The unity section was not found in the Web.config..
        /// </summary>
        internal static string UnitySectionNotFoundMessage {
            get {
                return ResourceManager.GetString("UnitySectionNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The alias {0} is not recognized as an alias for a lifetime manager..
        /// </summary>
        internal static string UnrecognizedLifetimeManagerAliasExceptionMessage {
            get {
                return ResourceManager.GetString("UnrecognizedLifetimeManagerAliasExceptionMessage", resourceCulture);
            }
        }
    }
}
