//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoTrade.Accounts.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TradingAccount
    {
        public TradingAccount()
        {
            this.Positions = new HashSet<TradingAccountPosition>();
            this.Transactions = new HashSet<TradingAccountTransaction>();
        }
    
        public int Id { get; set; }
        public int CashAccountId { get; set; }
        public int BrokerId { get; set; }
        public string Name { get; set; }
        public bool Enabled { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Modified { get; set; }
    
        public virtual Broker Broker { get; set; }
        public virtual CashAccount CashAccount { get; set; }
        public virtual ICollection<TradingAccountPosition> Positions { get; set; }
        public virtual ICollection<TradingAccountTransaction> Transactions { get; set; }
    }
}
