//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoTrade.Accounts.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TradingAccountTransaction
    {
        public int Id { get; set; }
        public int TradingAccountId { get; set; }
        public string Symbol { get; set; }
        public string Direction { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
        public int Status { get; set; }
        public System.DateTime SettleOn { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Modified { get; set; }
    
        public virtual TradingAccount TradingAccount { get; set; }
        public virtual TransactionStatu TransactionStatus { get; set; }
    }
}
