//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleImageSearchPOC
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.ServiceModel.DomainServices;
    using System.ServiceModel.DomainServices.Client;
    using System.ServiceModel.DomainServices.Client.ApplicationServices;
    
    
    /// <summary>
    /// Context for the RIA application.
    /// </summary>
    /// <remarks>
    /// This context extends the base to make application services and types available
    /// for consumption from code and xaml.
    /// </remarks>
    public sealed partial class WebContext : WebContextBase
    {
        
        #region Extensibility Method Definitions

        /// <summary>
        /// This method is invoked from the constructor once initialization is complete and
        /// can be used for further object setup.
        /// </summary>
        partial void OnCreated();

        #endregion
        
        
        /// <summary>
        /// Initializes a new instance of the WebContext class.
        /// </summary>
        public WebContext()
        {
            this.OnCreated();
        }
        
        /// <summary>
        /// Gets the context that is registered as a lifetime object with the current application.
        /// </summary>
        /// <exception cref="InvalidOperationException"> is thrown if there is no current application,
        /// no contexts have been added, or more than one context has been added.
        /// </exception>
        /// <seealso cref="System.Windows.Application.ApplicationLifetimeObjects"/>
        public new static WebContext Current
        {
            get
            {
                return ((WebContext)(WebContextBase.Current));
            }
        }
    }
}
namespace GoogleImageSearchPOC.Web
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.ServiceModel;
    using System.ServiceModel.DomainServices;
    using System.ServiceModel.DomainServices.Client;
    using System.ServiceModel.DomainServices.Client.ApplicationServices;
    
    
    /// <summary>
    /// The DomainContext corresponding to the 'SearchService' DomainService.
    /// </summary>
    public sealed partial class SearchContext : DomainContext
    {
        
        #region Extensibility Method Definitions

        /// <summary>
        /// This method is invoked from the constructor once initialization is complete and
        /// can be used for further object setup.
        /// </summary>
        partial void OnCreated();

        #endregion
        
        
        /// <summary>
        /// Initializes a new instance of the <see cref="SearchContext"/> class.
        /// </summary>
        public SearchContext() : 
                this(new WebDomainClient<ISearchServiceContract>(new Uri("GoogleImageSearchPOC-Web-SearchService.svc", UriKind.Relative)))
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="SearchContext"/> class with the specified service URI.
        /// </summary>
        /// <param name="serviceUri">The SearchService service URI.</param>
        public SearchContext(Uri serviceUri) : 
                this(new WebDomainClient<ISearchServiceContract>(serviceUri))
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the <see cref="SearchContext"/> class with the specified <paramref name="domainClient"/>.
        /// </summary>
        /// <param name="domainClient">The DomainClient instance to use for this DomainContext.</param>
        public SearchContext(DomainClient domainClient) : 
                base(domainClient)
        {
            this.OnCreated();
        }
        
        /// <summary>
        /// Asynchronously invokes the 'GetSearchResults' method of the DomainService.
        /// </summary>
        /// <param name="keywordText">The value for the 'keywordText' parameter of this action.</param>
        /// <param name="callback">Callback to invoke when the operation completes.</param>
        /// <param name="userState">Value to pass to the callback.  It can be <c>null</c>.</param>
        /// <returns>An operation instance that can be used to manage the asynchronous request.</returns>
        public InvokeOperation<IEnumerable<string>> GetSearchResults(string keywordText, Action<InvokeOperation<IEnumerable<string>>> callback, object userState)
        {
            Dictionary<string, object> parameters = new Dictionary<string, object>();
            parameters.Add("keywordText", keywordText);
            this.ValidateMethod("GetSearchResults", parameters);
            return ((InvokeOperation<IEnumerable<string>>)(this.InvokeOperation("GetSearchResults", typeof(IEnumerable<string>), parameters, true, callback, userState)));
        }
        
        /// <summary>
        /// Asynchronously invokes the 'GetSearchResults' method of the DomainService.
        /// </summary>
        /// <param name="keywordText">The value for the 'keywordText' parameter of this action.</param>
        /// <returns>An operation instance that can be used to manage the asynchronous request.</returns>
        public InvokeOperation<IEnumerable<string>> GetSearchResults(string keywordText)
        {
            Dictionary<string, object> parameters = new Dictionary<string, object>();
            parameters.Add("keywordText", keywordText);
            this.ValidateMethod("GetSearchResults", parameters);
            return ((InvokeOperation<IEnumerable<string>>)(this.InvokeOperation("GetSearchResults", typeof(IEnumerable<string>), parameters, true, null, null)));
        }
        
        /// <summary>
        /// Creates a new EntityContainer for this DomainContext's EntitySets.
        /// </summary>
        /// <returns>A new container instance.</returns>
        protected override EntityContainer CreateEntityContainer()
        {
            return new SearchContextEntityContainer();
        }
        
        /// <summary>
        /// Service contract for the 'SearchService' DomainService.
        /// </summary>
        [ServiceContract()]
        public interface ISearchServiceContract
        {
            
            /// <summary>
            /// Asynchronously invokes the 'GetSearchResults' operation.
            /// </summary>
            /// <param name="keywordText">The value for the 'keywordText' parameter of this action.</param>
            /// <param name="callback">Callback to invoke on completion.</param>
            /// <param name="asyncState">Optional state object.</param>
            /// <returns>An IAsyncResult that can be used to monitor the request.</returns>
            [FaultContract(typeof(DomainServiceFault), Action="http://tempuri.org/SearchService/GetSearchResultsDomainServiceFault", Name="DomainServiceFault", Namespace="DomainServices")]
            [OperationContract(AsyncPattern=true, Action="http://tempuri.org/SearchService/GetSearchResults", ReplyAction="http://tempuri.org/SearchService/GetSearchResultsResponse")]
            IAsyncResult BeginGetSearchResults(string keywordText, AsyncCallback callback, object asyncState);
            
            /// <summary>
            /// Completes the asynchronous operation begun by 'BeginGetSearchResults'.
            /// </summary>
            /// <param name="result">The IAsyncResult returned from 'BeginGetSearchResults'.</param>
            /// <returns>The 'IEnumerable`1' returned from the 'GetSearchResults' operation.</returns>
            IEnumerable<string> EndGetSearchResults(IAsyncResult result);
        }
        
        internal sealed class SearchContextEntityContainer : EntityContainer
        {
            
            public SearchContextEntityContainer()
            {
            }
        }
    }
}
