//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoTrade.MarketData.Data
{
    using System.Runtime.Serialization;
    using System;
    using System.Collections.Generic;
    
    [DataContract]
    public partial class ModuleDependency
    {
    	[DataMember]
        public int ID { get; set; }
    	[DataMember]
        public int ModuleID { get; set; }
    	[DataMember]
        public int DependentOnModuleID { get; set; }
    	[DataMember]
        public System.DateTime Created { get; set; }
    
    	[DataMember]
        public virtual Module DependentOnModule { get; set; }
    }
}
