//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoTrade.MarketData.Data
{
    using System.Runtime.Serialization;
    using System;
    using System.Collections.Generic;
    
    [DataContract]
    public partial class StockQuote
    {
    	[DataMember]
        public string Symbol { get; set; }
    	[DataMember]
        public System.DateTime QuoteDateTime { get; set; }
    	[DataMember]
        public decimal BidPrice { get; set; }
    	[DataMember]
        public decimal AskPrice { get; set; }
    	[DataMember]
        public decimal Change { get; set; }
    	[DataMember]
        public decimal OpenPrice { get; set; }
    	[DataMember]
        public System.DateTime Created { get; set; }
    	[DataMember]
        public int SubscriptionID { get; set; }
    	[DataMember]
        public decimal LastTradePrice { get; set; }
    
    	[DataMember]
        public virtual Subscription Subscription { get; set; }
    }
}
