//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoTrade.MarketData.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataProvider
    {
        public DataProvider()
        {
            this.Subscriptions = new HashSet<Subscription>();
        }
    
        public int ID { get; set; }
        public int ModuleID { get; set; }
        public string Type { get; set; }
        public bool Active { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Modified { get; set; }
    
        public virtual Module Module { get; set; }
        public virtual ICollection<Subscription> Subscriptions { get; set; }
    }
}
