//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Original file name:
// Generation date: 6/24/2013 6:05:28 PM
namespace AutoTrade.MarketData.Dashboard.DataService
{
    
    /// <summary>
    /// There are no comments for MarketDataRepository in the schema.
    /// </summary>
    public partial class MarketDataRepository : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialize a new MarketDataRepository object.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public MarketDataRepository(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("AutoTradeModel", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("AutoTrade.MarketData.Dashboard.DataService", typeName.Substring(14)), false);
            }
            return null;
        }
        /// <summary>
        /// Since the namespace configured for this service reference
        /// in Visual Studio is different from the one indicated in the
        /// server schema, use type-mappers to map between the two.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("AutoTrade.MarketData.Dashboard.DataService", global::System.StringComparison.Ordinal))
            {
                return string.Concat("AutoTradeModel.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// There are no comments for DataProviders in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<DataProvider> DataProviders
        {
            get
            {
                if ((this._DataProviders == null))
                {
                    this._DataProviders = base.CreateQuery<DataProvider>("DataProviders");
                }
                return this._DataProviders;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<DataProvider> _DataProviders;
        /// <summary>
        /// There are no comments for StockListProviders in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<StockListProvider> StockListProviders
        {
            get
            {
                if ((this._StockListProviders == null))
                {
                    this._StockListProviders = base.CreateQuery<StockListProvider>("StockListProviders");
                }
                return this._StockListProviders;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<StockListProvider> _StockListProviders;
        /// <summary>
        /// There are no comments for Subscriptions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Subscription> Subscriptions
        {
            get
            {
                if ((this._Subscriptions == null))
                {
                    this._Subscriptions = base.CreateQuery<Subscription>("Subscriptions");
                }
                return this._Subscriptions;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Subscription> _Subscriptions;
        /// <summary>
        /// There are no comments for DataProviders in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToDataProviders(DataProvider dataProvider)
        {
            base.AddObject("DataProviders", dataProvider);
        }
        /// <summary>
        /// There are no comments for StockListProviders in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToStockListProviders(StockListProvider stockListProvider)
        {
            base.AddObject("StockListProviders", stockListProvider);
        }
        /// <summary>
        /// There are no comments for Subscriptions in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToSubscriptions(Subscription subscription)
        {
            base.AddObject("Subscriptions", subscription);
        }
    }
    /// <summary>
    /// There are no comments for AutoTradeModel.DataProvider in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("DataProviders")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class DataProvider : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new DataProvider object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        /// <param name="type">Initial value of Type.</param>
        /// <param name="active">Initial value of Active.</param>
        /// <param name="created">Initial value of Created.</param>
        /// <param name="modified">Initial value of Modified.</param>
        /// <param name="name">Initial value of Name.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static DataProvider CreateDataProvider(int ID, string type, bool active, global::System.DateTime created, global::System.DateTime modified, string name)
        {
            DataProvider dataProvider = new DataProvider();
            dataProvider.ID = ID;
            dataProvider.Type = type;
            dataProvider.Active = active;
            dataProvider.Created = created;
            dataProvider.Modified = modified;
            dataProvider.Name = name;
            return dataProvider;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Type in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Type
        {
            get
            {
                return this._Type;
            }
            set
            {
                this.OnTypeChanging(value);
                this._Type = value;
                this.OnTypeChanged();
                this.OnPropertyChanged("Type");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Type;
        partial void OnTypeChanging(string value);
        partial void OnTypeChanged();
        /// <summary>
        /// There are no comments for Property Active in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool Active
        {
            get
            {
                return this._Active;
            }
            set
            {
                this.OnActiveChanging(value);
                this._Active = value;
                this.OnActiveChanged();
                this.OnPropertyChanged("Active");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _Active;
        partial void OnActiveChanging(bool value);
        partial void OnActiveChanged();
        /// <summary>
        /// There are no comments for Property Created in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime Created
        {
            get
            {
                return this._Created;
            }
            set
            {
                this.OnCreatedChanging(value);
                this._Created = value;
                this.OnCreatedChanged();
                this.OnPropertyChanged("Created");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _Created;
        partial void OnCreatedChanging(global::System.DateTime value);
        partial void OnCreatedChanged();
        /// <summary>
        /// There are no comments for Property Modified in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime Modified
        {
            get
            {
                return this._Modified;
            }
            set
            {
                this.OnModifiedChanging(value);
                this._Modified = value;
                this.OnModifiedChanged();
                this.OnPropertyChanged("Modified");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _Modified;
        partial void OnModifiedChanging(global::System.DateTime value);
        partial void OnModifiedChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for AutoTradeModel.StockListProvider in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("StockListProviders")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class StockListProvider : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new StockListProvider object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        /// <param name="type">Initial value of Type.</param>
        /// <param name="active">Initial value of Active.</param>
        /// <param name="created">Initial value of Created.</param>
        /// <param name="modified">Initial value of Modified.</param>
        /// <param name="name">Initial value of Name.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static StockListProvider CreateStockListProvider(int ID, string type, bool active, global::System.DateTime created, global::System.DateTime modified, string name)
        {
            StockListProvider stockListProvider = new StockListProvider();
            stockListProvider.ID = ID;
            stockListProvider.Type = type;
            stockListProvider.Active = active;
            stockListProvider.Created = created;
            stockListProvider.Modified = modified;
            stockListProvider.Name = name;
            return stockListProvider;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Type in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Type
        {
            get
            {
                return this._Type;
            }
            set
            {
                this.OnTypeChanging(value);
                this._Type = value;
                this.OnTypeChanged();
                this.OnPropertyChanged("Type");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Type;
        partial void OnTypeChanging(string value);
        partial void OnTypeChanged();
        /// <summary>
        /// There are no comments for Property Active in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool Active
        {
            get
            {
                return this._Active;
            }
            set
            {
                this.OnActiveChanging(value);
                this._Active = value;
                this.OnActiveChanged();
                this.OnPropertyChanged("Active");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _Active;
        partial void OnActiveChanging(bool value);
        partial void OnActiveChanged();
        /// <summary>
        /// There are no comments for Property Created in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime Created
        {
            get
            {
                return this._Created;
            }
            set
            {
                this.OnCreatedChanging(value);
                this._Created = value;
                this.OnCreatedChanged();
                this.OnPropertyChanged("Created");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _Created;
        partial void OnCreatedChanging(global::System.DateTime value);
        partial void OnCreatedChanged();
        /// <summary>
        /// There are no comments for Property Modified in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime Modified
        {
            get
            {
                return this._Modified;
            }
            set
            {
                this.OnModifiedChanging(value);
                this._Modified = value;
                this.OnModifiedChanged();
                this.OnPropertyChanged("Modified");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _Modified;
        partial void OnModifiedChanging(global::System.DateTime value);
        partial void OnModifiedChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for AutoTradeModel.Subscription in the schema.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Subscriptions")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class Subscription : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new Subscription object.
        /// </summary>
        /// <param name="ID">Initial value of ID.</param>
        /// <param name="name">Initial value of Name.</param>
        /// <param name="active">Initial value of Active.</param>
        /// <param name="updateInterval">Initial value of UpdateInterval.</param>
        /// <param name="dataProviderID">Initial value of DataProviderID.</param>
        /// <param name="stockListProviderID">Initial value of StockListProviderID.</param>
        /// <param name="created">Initial value of Created.</param>
        /// <param name="modified">Initial value of Modified.</param>
        /// <param name="timeOfDayStart">Initial value of TimeOfDayStart.</param>
        /// <param name="timeOfDayEnd">Initial value of TimeOfDayEnd.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Subscription CreateSubscription(int ID, string name, bool active, global::System.DateTime updateInterval, int dataProviderID, int stockListProviderID, global::System.DateTime created, global::System.DateTime modified, global::System.DateTime timeOfDayStart, global::System.DateTime timeOfDayEnd)
        {
            Subscription subscription = new Subscription();
            subscription.ID = ID;
            subscription.Name = name;
            subscription.Active = active;
            subscription.UpdateInterval = updateInterval;
            subscription.DataProviderID = dataProviderID;
            subscription.StockListProviderID = stockListProviderID;
            subscription.Created = created;
            subscription.Modified = modified;
            subscription.TimeOfDayStart = timeOfDayStart;
            subscription.TimeOfDayEnd = timeOfDayEnd;
            return subscription;
        }
        /// <summary>
        /// There are no comments for Property ID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// There are no comments for Property Name in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// There are no comments for Property Active in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public bool Active
        {
            get
            {
                return this._Active;
            }
            set
            {
                this.OnActiveChanging(value);
                this._Active = value;
                this.OnActiveChanged();
                this.OnPropertyChanged("Active");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private bool _Active;
        partial void OnActiveChanging(bool value);
        partial void OnActiveChanged();
        /// <summary>
        /// There are no comments for Property UpdateInterval in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime UpdateInterval
        {
            get
            {
                return this._UpdateInterval;
            }
            set
            {
                this.OnUpdateIntervalChanging(value);
                this._UpdateInterval = value;
                this.OnUpdateIntervalChanged();
                this.OnPropertyChanged("UpdateInterval");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _UpdateInterval;
        partial void OnUpdateIntervalChanging(global::System.DateTime value);
        partial void OnUpdateIntervalChanged();
        /// <summary>
        /// There are no comments for Property LastUpdated in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> LastUpdated
        {
            get
            {
                return this._LastUpdated;
            }
            set
            {
                this.OnLastUpdatedChanging(value);
                this._LastUpdated = value;
                this.OnLastUpdatedChanged();
                this.OnPropertyChanged("LastUpdated");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _LastUpdated;
        partial void OnLastUpdatedChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnLastUpdatedChanged();
        /// <summary>
        /// There are no comments for Property DataProviderID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int DataProviderID
        {
            get
            {
                return this._DataProviderID;
            }
            set
            {
                this.OnDataProviderIDChanging(value);
                this._DataProviderID = value;
                this.OnDataProviderIDChanged();
                this.OnPropertyChanged("DataProviderID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _DataProviderID;
        partial void OnDataProviderIDChanging(int value);
        partial void OnDataProviderIDChanged();
        /// <summary>
        /// There are no comments for Property StockListProviderID in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int StockListProviderID
        {
            get
            {
                return this._StockListProviderID;
            }
            set
            {
                this.OnStockListProviderIDChanging(value);
                this._StockListProviderID = value;
                this.OnStockListProviderIDChanged();
                this.OnPropertyChanged("StockListProviderID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _StockListProviderID;
        partial void OnStockListProviderIDChanging(int value);
        partial void OnStockListProviderIDChanged();
        /// <summary>
        /// There are no comments for Property Created in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime Created
        {
            get
            {
                return this._Created;
            }
            set
            {
                this.OnCreatedChanging(value);
                this._Created = value;
                this.OnCreatedChanged();
                this.OnPropertyChanged("Created");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _Created;
        partial void OnCreatedChanging(global::System.DateTime value);
        partial void OnCreatedChanged();
        /// <summary>
        /// There are no comments for Property Modified in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime Modified
        {
            get
            {
                return this._Modified;
            }
            set
            {
                this.OnModifiedChanging(value);
                this._Modified = value;
                this.OnModifiedChanged();
                this.OnPropertyChanged("Modified");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _Modified;
        partial void OnModifiedChanging(global::System.DateTime value);
        partial void OnModifiedChanged();
        /// <summary>
        /// There are no comments for Property TimeOfDayStart in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime TimeOfDayStart
        {
            get
            {
                return this._TimeOfDayStart;
            }
            set
            {
                this.OnTimeOfDayStartChanging(value);
                this._TimeOfDayStart = value;
                this.OnTimeOfDayStartChanged();
                this.OnPropertyChanged("TimeOfDayStart");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _TimeOfDayStart;
        partial void OnTimeOfDayStartChanging(global::System.DateTime value);
        partial void OnTimeOfDayStartChanged();
        /// <summary>
        /// There are no comments for Property TimeOfDayEnd in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime TimeOfDayEnd
        {
            get
            {
                return this._TimeOfDayEnd;
            }
            set
            {
                this.OnTimeOfDayEndChanging(value);
                this._TimeOfDayEnd = value;
                this.OnTimeOfDayEndChanged();
                this.OnPropertyChanged("TimeOfDayEnd");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _TimeOfDayEnd;
        partial void OnTimeOfDayEndChanging(global::System.DateTime value);
        partial void OnTimeOfDayEndChanged();
        /// <summary>
        /// There are no comments for DataProvider in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public DataProvider DataProvider
        {
            get
            {
                return this._DataProvider;
            }
            set
            {
                this._DataProvider = value;
                this.OnPropertyChanged("DataProvider");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private DataProvider _DataProvider;
        /// <summary>
        /// There are no comments for StockListProvider in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public StockListProvider StockListProvider
        {
            get
            {
                return this._StockListProvider;
            }
            set
            {
                this._StockListProvider = value;
                this.OnPropertyChanged("StockListProvider");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private StockListProvider _StockListProvider;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// There are no comments for ComplexType AutoTradeModel.SubscriptionQuoteSummary in the schema.
    /// </summary>
    public partial class SubscriptionQuoteSummary : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Create a new SubscriptionQuoteSummary object.
        /// </summary>
        /// <param name="subscriptionId">Initial value of SubscriptionId.</param>
        /// <param name="symbol">Initial value of Symbol.</param>
        /// <param name="quoteCount">Initial value of QuoteCount.</param>
        /// <param name="firstQuoted">Initial value of FirstQuoted.</param>
        /// <param name="lastQuoted">Initial value of LastQuoted.</param>
        /// <param name="latestPrice">Initial value of LatestPrice.</param>
        /// <param name="latestBid">Initial value of LatestBid.</param>
        /// <param name="latestAsk">Initial value of LatestAsk.</param>
        /// <param name="latestChange">Initial value of LatestChange.</param>
        /// <param name="latestOpen">Initial value of LatestOpen.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static SubscriptionQuoteSummary CreateSubscriptionQuoteSummary(int subscriptionId, string symbol, int quoteCount, global::System.DateTime firstQuoted, global::System.DateTime lastQuoted, decimal latestPrice, decimal latestBid, decimal latestAsk, decimal latestChange, decimal latestOpen)
        {
            SubscriptionQuoteSummary subscriptionQuoteSummary = new SubscriptionQuoteSummary();
            subscriptionQuoteSummary.SubscriptionId = subscriptionId;
            subscriptionQuoteSummary.Symbol = symbol;
            subscriptionQuoteSummary.QuoteCount = quoteCount;
            subscriptionQuoteSummary.FirstQuoted = firstQuoted;
            subscriptionQuoteSummary.LastQuoted = lastQuoted;
            subscriptionQuoteSummary.LatestPrice = latestPrice;
            subscriptionQuoteSummary.LatestBid = latestBid;
            subscriptionQuoteSummary.LatestAsk = latestAsk;
            subscriptionQuoteSummary.LatestChange = latestChange;
            subscriptionQuoteSummary.LatestOpen = latestOpen;
            return subscriptionQuoteSummary;
        }
        /// <summary>
        /// There are no comments for Property SubscriptionId in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int SubscriptionId
        {
            get
            {
                return this._SubscriptionId;
            }
            set
            {
                this.OnSubscriptionIdChanging(value);
                this._SubscriptionId = value;
                this.OnSubscriptionIdChanged();
                this.OnPropertyChanged("SubscriptionId");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _SubscriptionId;
        partial void OnSubscriptionIdChanging(int value);
        partial void OnSubscriptionIdChanged();
        /// <summary>
        /// There are no comments for Property Symbol in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Symbol
        {
            get
            {
                return this._Symbol;
            }
            set
            {
                this.OnSymbolChanging(value);
                this._Symbol = value;
                this.OnSymbolChanged();
                this.OnPropertyChanged("Symbol");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Symbol;
        partial void OnSymbolChanging(string value);
        partial void OnSymbolChanged();
        /// <summary>
        /// There are no comments for Property QuoteCount in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int QuoteCount
        {
            get
            {
                return this._QuoteCount;
            }
            set
            {
                this.OnQuoteCountChanging(value);
                this._QuoteCount = value;
                this.OnQuoteCountChanged();
                this.OnPropertyChanged("QuoteCount");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _QuoteCount;
        partial void OnQuoteCountChanging(int value);
        partial void OnQuoteCountChanged();
        /// <summary>
        /// There are no comments for Property FirstQuoted in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime FirstQuoted
        {
            get
            {
                return this._FirstQuoted;
            }
            set
            {
                this.OnFirstQuotedChanging(value);
                this._FirstQuoted = value;
                this.OnFirstQuotedChanged();
                this.OnPropertyChanged("FirstQuoted");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _FirstQuoted;
        partial void OnFirstQuotedChanging(global::System.DateTime value);
        partial void OnFirstQuotedChanged();
        /// <summary>
        /// There are no comments for Property LastQuoted in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime LastQuoted
        {
            get
            {
                return this._LastQuoted;
            }
            set
            {
                this.OnLastQuotedChanging(value);
                this._LastQuoted = value;
                this.OnLastQuotedChanged();
                this.OnPropertyChanged("LastQuoted");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _LastQuoted;
        partial void OnLastQuotedChanging(global::System.DateTime value);
        partial void OnLastQuotedChanged();
        /// <summary>
        /// There are no comments for Property LatestPrice in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public decimal LatestPrice
        {
            get
            {
                return this._LatestPrice;
            }
            set
            {
                this.OnLatestPriceChanging(value);
                this._LatestPrice = value;
                this.OnLatestPriceChanged();
                this.OnPropertyChanged("LatestPrice");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private decimal _LatestPrice;
        partial void OnLatestPriceChanging(decimal value);
        partial void OnLatestPriceChanged();
        /// <summary>
        /// There are no comments for Property LatestBid in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public decimal LatestBid
        {
            get
            {
                return this._LatestBid;
            }
            set
            {
                this.OnLatestBidChanging(value);
                this._LatestBid = value;
                this.OnLatestBidChanged();
                this.OnPropertyChanged("LatestBid");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private decimal _LatestBid;
        partial void OnLatestBidChanging(decimal value);
        partial void OnLatestBidChanged();
        /// <summary>
        /// There are no comments for Property LatestAsk in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public decimal LatestAsk
        {
            get
            {
                return this._LatestAsk;
            }
            set
            {
                this.OnLatestAskChanging(value);
                this._LatestAsk = value;
                this.OnLatestAskChanged();
                this.OnPropertyChanged("LatestAsk");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private decimal _LatestAsk;
        partial void OnLatestAskChanging(decimal value);
        partial void OnLatestAskChanged();
        /// <summary>
        /// There are no comments for Property LatestChange in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public decimal LatestChange
        {
            get
            {
                return this._LatestChange;
            }
            set
            {
                this.OnLatestChangeChanging(value);
                this._LatestChange = value;
                this.OnLatestChangeChanged();
                this.OnPropertyChanged("LatestChange");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private decimal _LatestChange;
        partial void OnLatestChangeChanging(decimal value);
        partial void OnLatestChangeChanged();
        /// <summary>
        /// There are no comments for Property LatestOpen in the schema.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public decimal LatestOpen
        {
            get
            {
                return this._LatestOpen;
            }
            set
            {
                this.OnLatestOpenChanging(value);
                this._LatestOpen = value;
                this.OnLatestOpenChanged();
                this.OnPropertyChanged("LatestOpen");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private decimal _LatestOpen;
        partial void OnLatestOpenChanging(decimal value);
        partial void OnLatestOpenChanged();
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
