//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoTrade.MarketData.Data
{
    using System.Runtime.Serialization;
    using System;
    using System.Collections.Generic;
    
    [DataContract]
    public partial class EmailFeedConfiguration
    {
    	[DataMember]
        public int ID { get; set; }
    	[DataMember]
        public string Host { get; set; }
    	[DataMember]
        public string UserName { get; set; }
    	[DataMember]
        public string Password { get; set; }
    	[DataMember]
        public string From { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> After { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> Before { get; set; }
    	[DataMember]
        public string SubjectKeywords { get; set; }
    	[DataMember]
        public string BodyKeywords { get; set; }
    	[DataMember]
        public System.TimeSpan PollingInterval { get; set; }
    	[DataMember]
        public System.TimeSpan EmailLifetime { get; set; }
    	[DataMember]
        public System.DateTime Created { get; set; }
    	[DataMember]
        public System.DateTime Modified { get; set; }
    	[DataMember]
        public string Folder { get; set; }
    	[DataMember]
        public string Protocol { get; set; }
    	[DataMember]
        public string Name { get; set; }
    }
}
