//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoTrade.MarketData.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial interface IMarketDataRepository
    {
         IDbSet<DataProvider> DataProviders { get; set; }
         IDbSet<Module> Modules { get; set; }
         IDbSet<ModuleDependency> ModuleDependencies { get; set; }
         IDbSet<Stock> Stocks { get; set; }
         IDbSet<StockListProvider> StockListProviders { get; set; }
         IDbSet<StockQuote> StockQuotes { get; set; }
         IDbSet<Subscription> Subscriptions { get; set; }
    
    	int SaveChanges();
    }
    
    public partial class MarketDataRepository : DbContext, IMarketDataRepository
    {
        public MarketDataRepository()
            : base("name=MarketDataRepository")
        {
            this.Configuration.LazyLoadingEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public IDbSet<DataProvider> DataProviders { get; set; }
        public IDbSet<Module> Modules { get; set; }
        public IDbSet<ModuleDependency> ModuleDependencies { get; set; }
        public IDbSet<Stock> Stocks { get; set; }
        public IDbSet<StockListProvider> StockListProviders { get; set; }
        public IDbSet<StockQuote> StockQuotes { get; set; }
        public IDbSet<Subscription> Subscriptions { get; set; }
    }
}
