//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoTrade.MarketData.Data
{
    using System.Runtime.Serialization;
    using System;
    using System.Collections.Generic;
    
    [DataContract]
    public partial class Stock
    {
        public Stock()
        {
            this.StockQuotes = new HashSet<StockQuote>();
        }
    
    	[DataMember]
        public string Symbol { get; set; }
    	[DataMember]
        public string CompanyName { get; set; }
    	[DataMember]
        public Nullable<int> Sector { get; set; }
    	[DataMember]
        public Nullable<int> Industry { get; set; }
    	[DataMember]
        public System.DateTime Created { get; set; }
    	[DataMember]
        public System.DateTime Modified { get; set; }
    
    	[DataMember]
        public virtual ICollection<StockQuote> StockQuotes { get; set; }
    }
}
