//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoTrade.MarketData.Data
{
    using System.Runtime.Serialization;
    using System;
    using System.Collections.Generic;
    
    [DataContract]
    public partial class Subscription
    {
        public Subscription()
        {
            this.Stocks = new HashSet<Stock>();
            this.StockQuotes = new HashSet<StockQuote>();
        }
    
    	[DataMember]
        public int ID { get; set; }
    	[DataMember]
        public string Name { get; set; }
    	[DataMember]
        public bool Active { get; set; }
    	[DataMember]
        public System.DateTime UpdateInterval { get; set; }
    	[DataMember]
        public Nullable<System.DateTime> LastUpdated { get; set; }
    	[DataMember]
        public int DataProviderID { get; set; }
    	[DataMember]
        public int StockListProviderID { get; set; }
    	[DataMember]
        public System.DateTime Created { get; set; }
    	[DataMember]
        public System.DateTime Modified { get; set; }
    	[DataMember]
        public System.DateTime TimeOfDayStart { get; set; }
    	[DataMember]
        public System.DateTime TimeOfDayEnd { get; set; }
    
    	[DataMember]
        public virtual DataProvider DataProvider { get; set; }
    	[DataMember]
        public virtual StockListProvider StockListProvider { get; set; }
    	[DataMember]
        public virtual ICollection<Stock> Stocks { get; set; }
    	[DataMember]
        public virtual ICollection<StockQuote> StockQuotes { get; set; }
    }
}
