//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoTrade.MarketData.Yahoo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoTrade.MarketData.Yahoo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV does not have the correct number of columns..
        /// </summary>
        internal static string CsvMissingColumnsMessage {
            get {
                return ResourceManager.GetString("CsvMissingColumnsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration section {0} was not found..
        /// </summary>
        internal static string CsvQueryConfigurationSectionMissingMessage {
            get {
                return ResourceManager.GetString("CsvQueryConfigurationSectionMissingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YQL query provided is null or empty..
        /// </summary>
        internal static string EmptyYqlQueryMessage {
            get {
                return ResourceManager.GetString("EmptyYqlQueryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The response returned by executing the YQL query is empty..
        /// </summary>
        internal static string EmptyYqlResponseMessage {
            get {
                return ResourceManager.GetString("EmptyYqlResponseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No format for the url was provided (url name = {0})..
        /// </summary>
        internal static string EndpointFormatNotFoundMessageFormat {
            get {
                return ResourceManager.GetString("EndpointFormatNotFoundMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to retrieve data from all registered Yahoo market data providers..
        /// </summary>
        internal static string FailedToRetrieveFromAllProvidersMessage {
            get {
                return ResourceManager.GetString("FailedToRetrieveFromAllProvidersMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred retrieving data from the following provider type: {0}..
        /// </summary>
        internal static string FailedToRetrieveFromProviderMessageFormat {
            get {
                return ResourceManager.GetString("FailedToRetrieveFromProviderMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred parsing the CSV response: {0}.
        /// </summary>
        internal static string InvalidCsvFormatMessageFormat {
            get {
                return ResourceManager.GetString("InvalidCsvFormatMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create absolute YQL execution url from {0}..
        /// </summary>
        internal static string InvalidYqlEndpointFormat {
            get {
                return ResourceManager.GetString("InvalidYqlEndpointFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse the YQL response xml. See inner exception for details..
        /// </summary>
        internal static string InvalidYqlResponseMessage {
            get {
                return ResourceManager.GetString("InvalidYqlResponseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No tags were provided to specify columns in the CSV..
        /// </summary>
        internal static string NoCsvTagsProvidedMessage {
            get {
                return ResourceManager.GetString("NoCsvTagsProvidedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No symbols were provided for the query..
        /// </summary>
        internal static string NoSymbolsProvidedMessage {
            get {
                return ResourceManager.GetString("NoSymbolsProvidedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The results returned by the query are null or blank..
        /// </summary>
        internal static string QueryResultsAreEmptyMessage {
            get {
                return ResourceManager.GetString("QueryResultsAreEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The url for the query is null or blank..
        /// </summary>
        internal static string QueryUrlNotProvidedMessage {
            get {
                return ResourceManager.GetString("QueryUrlNotProvidedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The YQL query failed. Please see inner exception for details..
        /// </summary>
        internal static string YqlQueryFailedMessage {
            get {
                return ResourceManager.GetString("YqlQueryFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A required node is missing in YQL response: {0}..
        /// </summary>
        internal static string YqlResultNodeMissingFormat {
            get {
                return ResourceManager.GetString("YqlResultNodeMissingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The YQL table is currently blocked. The message returned by Yahoo is: &quot;{0}&quot;..
        /// </summary>
        internal static string YqlTableBlockedMessageFormat {
            get {
                return ResourceManager.GetString("YqlTableBlockedMessageFormat", resourceCulture);
            }
        }
    }
}
