//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoTrade.MarketData
{
    using System;
    using System.Collections.Generic;
    
    public partial class StockQuote
    {
        public string Symbol { get; set; }
        public System.DateTime QuoteDateTime { get; set; }
        public decimal BidPrice { get; set; }
        public decimal AskPrice { get; set; }
        public decimal Change { get; set; }
        public decimal OpenPrice { get; set; }
    
        public virtual Stock Stock { get; set; }
    }
}
