//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoTrade.MarketData.Yahoo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoTrade.MarketData.Yahoo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YQL query provided is null or empty..
        /// </summary>
        internal static string EmptyYqlQueryMessage {
            get {
                return ResourceManager.GetString("EmptyYqlQueryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The response returned by executing the YQL query is empty..
        /// </summary>
        internal static string EmptyYqlResponseMessage {
            get {
                return ResourceManager.GetString("EmptyYqlResponseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create absolute YQL execution url from {0}..
        /// </summary>
        internal static string InvalidYqlEndpointFormat {
            get {
                return ResourceManager.GetString("InvalidYqlEndpointFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to parse the YQL response xml. See inner exception for details..
        /// </summary>
        internal static string InvalidYqlResponseMessage {
            get {
                return ResourceManager.GetString("InvalidYqlResponseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The response object returned by the request to the YQL endpoint returned null..
        /// </summary>
        internal static string NullYqlResponseMessage {
            get {
                return ResourceManager.GetString("NullYqlResponseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No format for the YQL url was provided..
        /// </summary>
        internal static string YqlEndpointFormatNotFoundMessage {
            get {
                return ResourceManager.GetString("YqlEndpointFormatNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The YQL query failed. Please see inner exception for details..
        /// </summary>
        internal static string YqlQueryFailedMessage {
            get {
                return ResourceManager.GetString("YqlQueryFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A required node is missing in YQL response: {0}..
        /// </summary>
        internal static string YqlResultNodeMissingFormat {
            get {
                return ResourceManager.GetString("YqlResultNodeMissingFormat", resourceCulture);
            }
        }
    }
}
